#!/usr/bin/env php
<?php
/**
 * 系统入口程序
 * @name  run
 * @author  xwx
 */

 
if ($argc < 2) {
    die(<<<USAGE
Code Generetor Version 1.0.0
Usage:
{$argv[0]} ApplicationName [ApplicationPath]
USAGE
);
}

require __DIR__.'/code/config/config.php';

$config = include ROOT_PATH . '/code/config/dbconfig.php';

$application = new library\App($config);
$exitCode = $application->run();
exit($exitCode);