#!/usr/bin/env php
<?php
/**
 * 系统入口程序
 * @name  run
 * @author  xwx
 */

$helpMsg = <<<EOT
Usage:
    php run [options] [arguments]
Options:
    run                            runs
    clear                          Clear the project download data (including the database)
    install                        install
EOT;
 
if ($argc < 2) {
 
    die($helpMsg);
}

require __DIR__.'/code/config/config.php';

$config = include ROOT_PATH . '/code/config/dbconfig.php';

$application = new crawl\library\App($config);
$exitCode = $application->run();
exit($exitCode);